### ISSUE TITLE
when trying to convert i get an error

### ISSUE THREAD

**Issue by S0apyy** [Weebifying/2.2tpconvert#2]
so i tried converting a pack of mine(only the icons) and it gave this error 
![image](https://github.com/Weebifying/2.2tpconvert/assets/122272512/f24a6139-dd2b-4f01-ad86-1a3022026602)

**Comment by Weebifying** [comment]
god why did the plist maker of your gamesheetglow put in a random 100th ufo in even though theres only 35 just remove the entire key in the plist or rename it or smth but i can fix it for u if u just drop your files here

**Comment by S0apyy** [comment]
> god why did the plist maker of your gamesheetglow put in a random 100th ufo in even though theres only 35 just remove the entire key in the plist or rename it or smth but i can fix it for u if u just drop your files here

probably because its a texture pack that was made for sai modpack

**Comment by S0apyy** [comment]
i only need like 2 icons from it though

**Comment by S0apyy** [comment]
ill be able to send the texture pack later today though

**Comment by Weebifying** [comment]
> > god why did the plist maker of your gamesheetglow put in a random 100th ufo in even though theres only 35 just remove the entire key in the plist or rename it or smth but i can fix it for u if u just drop your files here
> 
> probably because its a texture pack that was made for sai modpack

ok but only the glow had the 100th ufo :sob:

**Comment by S0apyy** [comment]
ok @Weebifying weird thing, ive found a texturepack with the icons i want, but whenever i try to load in any icon that i converted in gd 2.2 it just crashes

**Comment by Weebifying** [comment]
> edit: nvm its plist stuff
so is your problem resolved?

**Comment by S0apyy** [comment]
> > edit: nvm its plist stuff
> 
> so is your problem resolved?
> 

yeah
