### ISSUE TITLE
Seems not to port while theres a glow sheet and GJ_Gamesheet02

### ISSUE THREAD

**Issue by daisuke1227** [Weebifying/2.2tpconvert#5]
Enter your 2.1 pack path: /home/bauzadaisuke/Blueskii/Ported/
Converted textures are saved in /home/bauzadaisuke/Blueskii/Ported/output!
Press Enter to close the window

i checked inside the output folder and theres nothing in there (i ported to HD)
[Ported.zip](https://github.com/Weebifying/2.2tpconvert/files/15196047/Ported.zip)

**Comment by daisuke1227** [comment]
never mind there is no glow sheet in there

**Comment by Weebifying** [comment]
LOL :sob:
